import { type NextPage } from "next";
import Head from "next/head";

import { FondoLogin, Header } from "~/components";

const Login: NextPage = () => {


  return (
    <>
      <Head>
        <title>Login | Talent Corner</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <FondoLogin />
    </>
  );
};

export default Login;
