import { type NextPage } from "next";
import Head from "next/head";

import { LoginForm, MainLayout, Preguntas, Titulos } from "~/components";

const Login: NextPage = () => {


  return (
    <>
      <Head>
        <title>Ayuda Ez-Cast | Talent Corner</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Titulos />
        <Preguntas /> 
      </MainLayout>
    </>
  );
};

export default Login;
