import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';

const COMMON_TEXTS: {[lang: string]: {[key: string]: string}} = {
    en: {
        o: 'or',
        regresar_paso: 'Previous step',
        paso_siguiente: 'Next step',
        guardar_y_terminar_mas_tarde: 'Save and finish later',
        finalizar: 'Finish',
        field_cant_be_empty: 'The [CAMPO] cant be empty',
        nombre: 'Name', 
        union: 'Union',
        ubicacion: 'Location',
        biografia: 'Biography',
        cambiar: 'Change',
        foto: 'Photo',
        edad: 'Age',
        agencia: 'Agency',
        telefono: 'Telephone',
        correo_electronico: 'Email',
        archivo: 'File',
        carta_responsiva: 'Responsive Letter',
        cv: 'CV',
        subir: 'Upload',
        arrastrar_archivos: 'Drag files in the box',
        si: 'Yes',
        no: 'No',
        cerrar_sesion: 'Sign Out', 
        selecciona_una_opcion: 'Select an option',
        cancelar: 'Cancel',
        guardar: 'Save',
        no_registros: 'There is no data',
        descargar: 'Download',
        proximamente: 'comming soon',
        conoce_mas: 'learn more',
        çazatalentos : 'Headhunter',
        talento: 'Talent',
        representante: 'Representative',
        paso : 'Step',
        peso: 'Weight',
        altura: 'Height',
        perfil: 'Profile',
        tus_aplicaciones: 'Applications',
        grabar_selftape: 'Record Self-Tape',
        mensajes: 'Messages',
        ayuda: 'Help',
        editar: 'Edit',
        info_basica: 'Basic information',
        media: 'Media',
        credito: 'Credit',
        credito_destacado: 'Featured Credit',
        creditos_destacados: 'Featured Credits',
        habilidades: 'Skills',
        habilidad: 'Skill',
        medidas: 'Measurements',
        activos: 'Assets',
        preferencias_roles: 'Role preferences',
        galeria_imagenes: 'Image gallery',
        agregar: 'Add',
        imagen: 'Image',
        video: 'Video',
        audio: 'Audio',
        selftape: 'Selftape',
        usuario_no_ha_capturado: `You haven't captured any [TYPE] yet`,
        titulo: 'Title',
        rol: 'Role',
        director: 'Director',
        anio: 'Year',
        clip: 'Clip',
        destacado: 'Featured',
        mascotas: 'Pets',
        tipo: 'Type',
        raza: 'Breed',
        tamanio: 'Size',
        vehiculos: 'Vehicles',
        marca: 'Brand',
        modelo: 'Model',
        color: 'Color',
        vestuarios: 'Clothing',
        tipo_especifico: 'Specific Type',
        descripcion: 'Description',
        props: 'Props',
        equipo_deportivo: 'Sports Equipment',
        apariencia: 'Appearance',
        rango_de_edad_a_interpretar: 'Age range to portray',
        se_identifica_como: 'Identifies as',
        interesado_en_interpretar: 'Interested in performing',
        apariencia_etnica: 'Ethnic appearance',
        nacionalidad_etnia: 'Nationality / Ethnicity',
        color_de_cabello: 'Hair Color',
        dispuesto_a_cambiar_de_color_de_cabello: 'Willing to change hair color',
        estilo_de_cabello: 'Hairstyle',
        dispuesto_a_cortar_cabello: 'Willing to cut hair',
        vello_facial: 'Facial hair',
        dispuesto_a_crecer_o_afeitar_vello_facial: 'Willing to grow or shave facial hair',
        color_de_ojos: 'Eye color',
        tatuajes: 'Tattoos',
        piercings: 'Piercings',
        gemelo_o_trillizo: 'Twin or Triplet',
        atributos_o_condiciones_unicas: 'Unique attributes or conditions',
        medidas_vestuario: 'Clothing Measurements',
        generales: 'General',
        hombre: 'Man',
        mujer: 'Woman',
        nino: 'Boy',
        nina: 'Girl',
        entrepierna: 'Crotch',
        guantes: 'Gloves',
        sombrero: 'Hat',
        pecho: 'Chest',
        cuello: 'Neck',
        mangas: 'Sleeves',
        saco: 'Jacket',
        playera: 'Shirt',
        calzado: 'Shoes',
        vestido: 'Dress',
        busto: 'Bust',
        copa: 'Cup',
        cadera: 'Hip',
        pants: 'Pants',
        bebe: 'Baby',
        mes: 'Month',
        meses: 'Months',
        largo: 'length',
        tipo_de_trabajo: 'Type of work',
        trabajo_de_extra: 'Work as an extra',
        locacion_de_trabajo_principal: 'Main Work Location',
        locaciones_de_trabajo_adicionales: 'Additional Work Locations',
        interes_en_proyectos_pagados: 'Interest in paid projects',
        interes_en_proyectos_no_pagados: 'Interest in unpaid projects',
        nombre_de_representante: `Representative's Name`,
        documentos: 'Documents',
        disponibilidad_para: 'Availability for',
        otras_profesiones: 'Other professions',
        meses_de_embarazo: 'Months of pregnancy',
        pagina_web: 'Webpage',
        links_a_redes: 'Links to social media',
    },
    es: {
        o: 'o',
        regresar_paso: 'Regresar paso',
        paso_siguiente: 'Siguiente paso',
        guardar_y_terminar_mas_tarde: 'Guardar y terminar más tarde',
        finalizar: 'Finalizar',
        nombre: 'Nombre',
        union: 'Unión',
        ubicacion: 'Ubicación',
        biografia: 'Biografía',
        field_cant_be_empty: 'El [CAMPO] no puede estar vacio',
        cambiar: 'Cambiar',
        foto: 'Foto',
        edad: 'Edad',
        agencia: 'Agencia',
        telefono: 'Teléfono',
        correo_electronico: 'Correo electrónico',
        archivo: 'Archivo',
        carta_responsiva: 'Carta Responsiva',
        cv: 'CV',
        subir: 'Subir',
        arrastrar_archivos: 'Arrastrar archivo(s) al recuadro',
        si: 'Si',
        no: 'No',
        cerrar_sesion: 'Cerrar Sesión',
        selecciona_una_opcion: 'Selecciona una opción',
        cancelar: 'Cancelar',
        guardar: 'Guardar',
        no_registros: 'No hay registros',
        descargar: 'Descargar',
        proximamente: 'proximamente',
        conoce_mas: 'conoce más',
        çazatalentos : 'Cazatalentos',
        talento : 'Talento',
        representante : 'Representante',
        paso : 'Paso',
        peso: 'Peso',
        altura: 'Altura',
        perfil: 'Perfil',
        tus_aplicaciones: 'Tus Aplicaciones',
        grabar_selftape: 'Grabar Self-Tape',
        mensajes: 'Mensajes',
        ayuda: 'Ayuda',
        editar: 'Editar',
        info_basica: 'Información básica',
        media: 'Media',
        credito: 'Crédito',
        credito_destacado: 'Crédito Destacado',
        creditos_destacados: 'Créditos Destacados',
        habilidades: 'Habilidades',
        habilidad: 'Habilidad',
        medidas: 'Medidas',
        activos: 'Activos',
        preferencias_roles: 'Preferencia de roles',
        galeria_imagenes: 'Galería de imágenes',
        agregar: 'Agregar',
        imagen: 'Imagen',
        video: 'Video',
        audio: 'Audio',
        selftape: 'Selftape',
        usuario_no_ha_capturado: 'No has capturado aún ningún [TYPE]',
        titulo: 'Titulo',
        rol: 'Rol',
        director: 'Director',
        anio: 'Año',
        clip: 'Clip',
        destacado: 'Destacado',
        mascotas: 'Mascotas',
        tipo: 'Tipo',
        raza: 'Raza',
        tamanio: 'Tamaño',
        vehiculos: 'Vehiculos',
        marca: 'Marca',
        modelo: 'Modelo',
        color: 'Color',
        vestuarios: 'Vestuarios',
        tipo_especifico: 'Tipo Especifico',
        descripcion: 'Descripcion',
        props: 'Props',
        equipo_deportivo: 'Equipo Deportivo',
        apariencia: 'Apariencia',
        rango_de_edad_a_interpretar: 'Rango de edad a interpretar',
        se_identifica_como: 'Se identifica como',
        interesado_en_interpretar: 'Interesado en interpretar',
        apariencia_etnica: 'Apariencia étnica',
        nacionalidad_etnia: 'Nacionalidad / Etnia',
        color_de_cabello: 'Color de Cabello',
        dispuesto_a_cambiar_de_color_de_cabello: 'Dispuesto a cambiar de color de cabello',
        estilo_de_cabello: 'Estilo de Cabello',
        dispuesto_a_cortar_cabello: 'Dispuesto a cortar cabello',
        vello_facial: 'Vello Facial',
        dispuesto_a_crecer_o_afeitar_vello_facial: 'Dispuesto a crecer o afeitar vello facial',
        color_de_ojos: 'Color de ojos',
        tatuajes: 'Tatuajes',
        piercings: 'Piercings',
        gemelo_o_trillizo: 'Gemelo o trillizo',
        atributos_o_condiciones_unicas: 'Atributos o condiciones únicas',
        medidas_vestuario: 'Medidas Vestuario',
        generales: 'Generales',
        hombre: 'Hombre',
        mujer: 'Mujer',
        nino: 'Niño',
        nina: 'Niña',
        entrepierna: 'Entrepierna',
        guantes: 'Guantes',
        sombrero: 'Sombrero',
        pecho: 'Pecho',
        cuello: 'Cuello',
        mangas: 'Mangas',
        saco: 'Saco',
        playera: 'Playera',
        calzado: 'Calzado',
        vestido: 'Vestido',
        busto: 'Busto',
        copa: 'Copa',
        cadera: 'Cadera',
        pants: 'Pants',
        bebe: 'Bebé',
        mes: 'Mes',
        meses: 'Meses',
        largo: 'Largo',
        tipo_de_trabajo: 'Tipo de trabajo',
        trabajo_de_extra: 'Trabajo de Extra',
        locacion_de_trabajo_principal: 'Locación de Trabajo Principal',
        locaciones_de_trabajo_adicionales: 'Locaciónes de Trabajo Adicionales',
        interes_en_proyectos_pagados: 'Interés en proyectos pagados',
        interes_en_proyectos_no_pagados: 'Interés en proyectos no pagados',
        nombre_de_representante: 'Nombre de Representante',
        documentos: 'Documentos',
        disponibilidad_para: 'Disponibilidad para',
        otras_profesiones: 'Otras profesiones',
        meses_de_embarazo: 'Meses de embarazo',
        pagina_web: 'Página web',
        links_a_redes: 'Link a redes sociales',
    }
}

const TEXTS_BY_PATHNAME: {[path: string]: {[lang: string]: {[key: string]: string}}} = {
    '/': {
        en: {
            slide_1: `<p className="h2">MAKE FILMS AND MORE</p>
            <p>"When you embark on a project, a dream, a goal, every piece is important, and like a puzzle, it's crucial to find the pieces that fit together and add value to your project.</p>
            <p>In Talent Corner®, discover incredible tools that will help you bring that vision to reality. Don't let anyone close the door on you and create opportunities that many can only imagine!"</p>`,
            slide_2: `<p className="m-0 talent_corner">
            Talent Corner® is a digital platform that functions as a <strong>Match Maker</strong> tool in various areas and fields of production, enabling the creation, filmmaking, or showcasing of your talent. It brings together aspiring individuals who are looking to take their first steps in the artistic world, whether independently or professionally, as well as experienced individuals seeking to facilitate, streamline, and carry out their film productions in a more organized and intelligent manner.
            <br /><br />
            Talent Corner® consists of 3 different sections, each with tools targeting different audiences, all encompassing the same community with a shared purpose in this Talent Corner.
            <br /><br />
            These sections are: <em>EZ-CAST</em>, <em>TREEHOUSE</em>, and <em>TALENT+</em>.
            <br /><br />
            Talent Corner® offers professional tools and formats at your disposal to collaborate on and execute projects of all kinds, from script to the big screen! Talent Corner® also serves as a self-promotion tool!</p>`,
            slide_4: `EZ-CAST, the place for those who want to discover and be discovered, CASTINGS`,
            slide_6: `A better way to search, find, and rent locations!`,
            slide_8: `Find the right freelance professional to start working on your project in minutes. A whole world of freelance talent at your fingertips.`,
        },
        es: {
            slide_1: `<p className="h2">HAZ CINE Y MÁS</p>
            <p>“Cuando te embarcas en un proyecto, un sueño, una meta, cada pieza es importante y como un  rompecabezas, es clave encontrar las piezas que embonen y sumen a tu proyecto.</p>
            <p>En Talent Corner® descubre herramientas increíbles que te ayudarán a traer esa visión a la realidad. ¡Que nadie te cierre la puerta y crea las oportunidades que muchos solo imaginan!” </p>`,
            slide_2: `<p className="m-0 talent_corner">
            Talent Corner® es una plataforma digital que funciona como herramienta de Match Maker a nivel producción en diferentes espacios y ámbitos, para crear, hacer cine o exponer tu talento, reuniendo así a aspirantes que buscan dar sus primeros pasos en el mundo artístico tanto a nivel independiente como profesional, así como personas con experiencia que busquen facilitar, agilizar y realizar sus producciones cinematográficas de una manera más organizada e inteligente.
            <br /><br />
            Talent Corner® consta de 3 diferentes secciones, herramientas que van dirigidas a diferente público, englobando un mismo gremio con una misma finalidad en esta Esquina del Talento.
            <br /><br />
            Estas son: EZ-CAST, TREEHOUSE Y TALENT +
            <br /><br />
            Talent Corner® pone a su disposición herramientas y formatos profesionales para sumar y ejecutar proyectos de todo tipo, ¡Del guión a la pantalla grande! ¡Talent Corner®  sirve también como herramienta de AUTOPROMOCIÓN!</p>`,
            slide_4: `EZ-CAST el lugar para los que quieren encontrar y ser encontrados, CASTINGS`,
            slide_6: `¿Una mejor manera de buscar, encontrar, rentar locaciones!`,
            slide_8: `Encuentra al profesional independiente adecuado para comenzar a trabajar en su proyecto en minutos. Todo un mundo de talento autónomo a tu alcance.`,
        }
    },
    '/registro': {
        en: {
            Titulo: 'EZ-CAST REGISTRATION',
            return: 'BACK TO EZ-CAST INFORMATION',
            paso_1: '1',
            crea_perfil : 'Create your profile',
            nombre : 'Name*',
            apellidos : 'Lastname*',
            usuario : 'User*',
            mail : 'E-mail',
            contra : 'Password',
            confirma_contra : 'Confirm Password',
            registrar_con : 'Or register with',
            siguiente_paso : 'Next Step ',
            nombre_corto : 'The name is too short',
            apellido_corto : 'The lastname is too short',
            usuario_corto : 'The username is too short',
            mail_invalido : 'The email is invalid',
            contra_corta : 'The password is too short',
            contra_diferente : 'The passwords are not the same',
            paso_2 : '2',
            tipo_membresia : 'Type of membresia',
            gratis : 'Free',
            anual : 'Annual',
            mensual : 'Monthly',
            pago : 'Pay',
            forma_pago : 'Way to pay',
        },
        es: {
            Titulo: 'REGISTRO EZ-CAST',
            return: 'REGRESAR A INFORMACIÓN EZ-CAST',
            paso_1: '1',
            crea_perfil : 'Crea tu perfil',
            nombre : 'Nombre*',
            apellidos : 'Apellidos*',
            usuario : 'Usuario*',
            mail : 'Correo electrónico',
            contra : 'Contraseña',
            confirma_contra : 'Confirmar Contraseña',
            registrar_con : 'O registrate con',
            siguiente_paso : 'Siguiente Paso ',
            nombre_corto : 'El nombre es demasiado corto',
            apellido_corto : 'El apellido es demasiado corto',
            usuario_corto : 'El usuario es demasiado corto',
            mail_invalido : 'El email es invalido',
            contra_corta : 'La contraseña es demasiado corta',
            contra_diferente : 'Las contraseñas no son la misma',
            paso_2 : '2',
            tipo_membresia : 'Tipo de membresía',
            gratis : 'Gratis',
            anual : 'Anual',
            mensual : 'Mensual',
            pago : 'Pago',
            forma_pago : 'Forma de pago',
        }
    },
    '/login': {
        en: {
            no_tienes_cuenta: 'You do not have an account?',
            registrate: 'Sign up here',
            mail: 'User / Email',
            password: 'Password',
            fgtpswd: 'Forgot your password?',
            restablecer: 'Restore',
            ingresar_como: 'Login as',
            accede_con: 'Or access with',
            necesitas_ayuda: 'Need help?',
            accede_a :'Access our',
            tutoriales : 'tutorials and frequently asked questions',
            descripción_cazatalentos : 'Profile for the person who seeks to "hunt" a person who meets the requirements and the talent that he needs.',
            descripcion_talento : 'Profile for the person looking to appear on screen and film projects.',
            descripcion_representante : 'Profile for the person who seeks to facilitate the connection with their talents and find more opportunities for them.',
        },
        es: {
            no_tienes_cuenta: 'No tienes cuenta?',
            registrate: 'Registrate aquí',
            mail: 'Usuario / Email',
            password: 'Contraseña',
            fgtpswd: 'Olvido su contraseña?',
            restablecer: 'Restablecer',
            ingresar_como: 'Ingresar como',
            accede_con: 'O accede con',
            necesitas_ayuda: 'Necesitas ayuda?',
            accede_a : 'Accede a nuestros',
            tutoriales : 'tutoriales y preguntas frecuentes.',
            descripción_cazatalentos : 'Perfil para la persona que busca “cazar” a una persona que cumpla con los requerimientos y el talento que éste necesita.',
            descripcion_talento : 'Perfil para la persona que busca aparecer en pantalla y proyectos de filmación.',
            descripcion_representante : 'Perfil para la persona que busca facilitar la conexión con sus talentos y encontrar más oportunidades para los mismos.',
        }
    },
    '/inicio': {
        en: {
            proyectos_activos: 'Active Projects',
            ahora_siendo_casteado: 'Now being cast...',
            destacados: 'Featured',
            ahora_castenado_en_ezcast: 'Now casting on EZ-Cast',
            continuar_a_ezcast: 'Continue to EZ-Cast'
        },
        es: {
            proyectos_activos: 'Proyectos Activos',
            ahora_siendo_casteado: 'Ahora siendo casteado…',
            destacados: 'destacados',
            ahora_castenado_en_ezcast: 'Ahora casteando en EZ-Cast',
            continuar_a_ezcast: 'Continuar a EZ-Cast'
        }
    },
    '/talento/dashboard': {
        en: {
            acerca_de: 'About Us',
            dialog_medidas_vestuario_subtitulo: 'Choose the category that applies to you.',
            calzado_ninos: 'Children Shoes'
        },
        es: {
            acerca_de: 'Acerca de',
            dialog_medidas_vestuario_subtitulo: 'Elige la categoría que aplique para ti.',
            calzado_ninos: 'Calzado Niños'
        }
    },
    '/talento/editar-perfil': {
        en: {
            step6_title: 'Role Preferences And Compensations',
            step7_title: 'Appareance Filters',
            nombre_union: `Union's Name`,
            eres_menor_de_edad: 'Are you a minor',
            datos_representante: 'Data of legal representative or guardian',
            info_medidas: 'Later on, you can add clothing measurements in the final view of your profile',
            elegir_foto_perfil: 'Select profile photo',
            media_fotos_tooltip: 'Test',
            media_videos_tooltip_titulo: 'Add a videobook or reel.',
            media_videos_tooltip_body: `A reel consists of editing together a clip that highlights your on-stage moments from later works. We recommend being clear and direct, seeking the best quality in audio and video, and compiling your best works to contrast and showcase.`,
            media_audios_tooltip: 'Showcase in a short audio your vocal ability; accents, imitations, voices, singing, etc...'
        },
        es: {
            step6_title: 'Preferencia de rol y compensación',
            step7_title: 'Filtros de Apariencia',
            nombre_union: 'Nombre Unión',
            eres_menor_de_edad: 'Eres menor de edad',
            datos_representante: 'Datos de representante o tutor legal',
            info_medidas: 'Más adelante, puedes agregar medidas para vestuario en la vista final de tu perfil',
            elegir_foto_perfil: 'Eligir foto de perfil',
            info_basica_biografia_tooltip_title: "", 
            media_fotos_tooltip: 'Prueba',
            media_videos_tooltip_titulo: 'Añade un videobook o Reel',
            media_videos_tooltip_body: `Un reel consiste en montar un clip editado que destaque tus
            momentos en escena de trabajos posteriores, te recomendamos
            ser claro y directo, buscar la mejor calidad en Audio y
            Video contrastando y recopilando tus mejores trabajos`,
            media_audios_tooltip: 'Resalta en un breve audio tu habilidad vocal; acentos, imitaciones, voces, canto, etc...'
        }
    }
}


const useLang = (lang: string) => {

    const route = useRouter();

    const [texts, setTexts] = useState<{[key: string]: string}>({});

    useEffect(() => {
        if (TEXTS_BY_PATHNAME[route.pathname]) {
            const by_path = TEXTS_BY_PATHNAME[route.pathname];
            if (by_path) {
                const by_lang = by_path[lang];
                const common = COMMON_TEXTS[lang];
                setTexts((by_lang) ? {...by_lang, ...common} : {});
            } else {
                setTexts({});
            }
        } else {
            setTexts({});
        }
    }, [lang, route.pathname]);

    return texts;
};

export default useLang;