import { useRouter } from "next/router";
import { useState, useEffect } from "react";

export const COMMON_TEXTS: { [lang: string]: { [key: string]: string } } = {
  en: {
    agencia_publicidad: "Advertising agency",
    casa_productora: "Production House",
    productor: "Producer",
    nuevo_proyecto: "New Project",
    alertas: "Your alerts",
    agenda_virtual: "Virtual diary",
    mis_proyectos: "My projects",
    editar_perfil: "Edit profile",
    fecha: "Date",
    bienvenido: "Welcome",
    atencion: "Attention",
    activar: "Activate",
    publico: "Public",
    privado: "Private",
    lineas: "Lines",
    no_visto: "Not Seen",
    visto: "Seen",
    audicion: "Audition",
    status: "Status",
    campo_no_definido: "[N] is not defined, please contact support",
    ciudad: "City",
    estado: "State",
    no_tienes_elementos: "you dont have any [N]",
    revisa: "Review",
    locacion_de_casting_y_fechas: "Casting location and dates",
    locacion_de_filmacion_y_fechas: "Filming location and dates",
    presentacion_solicitud: "Application submission",
    informacion_trabajo_y_notas: "Job information/notes",
    requisitos: "Requirements",
    archivos_adicionales: "Additional files",
    desnudos_o_situaciones_sexuales: "Nudity or sexual situations",
    detalles: "Details",
    tu: "Your",
    aplicacion: "Application",
    aplicaciones: "Applications",
    nota: "Note",
    una: "One",
    aplicado: "Applied",
    aplicar: "Apply",
    no_especificado: "Not Specified",
    compatibilidad_text: "Compatibility with your profile",
    fecha_limite_entrega_de_aplicaciones: "Application submission deadline",
    aceptando_aplicaciones_de: "Accepting applications from",
    inicio_de_proyecto: "Project start date",
    en: "In",
    proyecto_por: "Project By",
    ver: "See",
    desde_hasta: "From [N1] to [N2]",
    cerrar: "Close",
    pagado: "Paid",
    no_pagado: "Unpaid",
    de: "Of",
    confirmar: "Confirm",
    todos: "All",
    rango_edad: "Age Range",
    genero_rol: "Role Genre",
    tipo_rol: "Role Type",
    preferencia_pago: "Payment Prefference",
    buscar: "Search",
    PAGINADOR_RESULTS_LABEL: "[N1] of [N2] total results",
    PAGINADOR_ENTRIES_PER_PAGE: "Show [N] results per page",
    pagina: "Page",
    filtros: "Filters",
    FILES_ERRORS_FILE_ALREADY_EXISTS: "This file is already added",
    FILES_ERRORS_FILE_TOO_BIG:
      "This file has surpassed the space limit of [SIZE] kb",
    FILES_ERRORS_MAX_FILES_REACHED:
      "The limit of [MAX_FILES] files has been surpassed",
    particularidades: "Peculiarities",
    visibilidad: "Visibility",
    profesion: "Proffesion",
    otro: "Other",
    contacto: "Contact",
    principal: "Principal",
    adicional: "Additional",
    seleccionar_todos: "Select All",
    registros_por_pagina: "Entries Per Page",
    o: "or",
    pagina_anterior: "Previous Page",
    siguiente_pagina: "Next Page",
    regresar_paso: "Previous step",
    paso_siguiente: "Next step",
    guardar_y_terminar_mas_tarde: "Save and finish later",
    finalizar: "Finish",
    field_cant_be_empty: "The [CAMPO] cant be empty",
    nombre: "Name",
    union: "Union",
    ubicacion: "Location",
    biografia: "Biography",
    cambiar: "Change",
    foto: "Photo",
    edad: "Age",
    eliminar: "Delete",
    tipo_proyecto: "Proyect Type",
    agencia: "Agency",
    telefono: "Telephone",
    correo_electronico: "Email",
    archivo: "File",
    carta_responsiva: "Responsive Letter",
    cv: "CV",
    chico: "Small",
    mediano: "Medium",
    grande: "Large",
    subir: "Upload",
    arrastrar_archivos: "Drag files in the box",
    si: "Yes",
    no: "No",
    cerrar_sesion: "Sign Out",
    selecciona_una_opcion: "Select an option",
    cancelar: "Cancel",
    guardar: "Save",
    no_registros: "There is no data",
    descargar: "Download",
    proximamente: "comming soon",
    conoce_mas: "learn more",
    çazatalentos: "Headhunter",
    talento: "Talent",
    representante: "Representative",
    paso: "Step",
    peso: "Weight",
    altura: "Height",
    perfil: "Profile",
    tus_aplicaciones: "Applications",
    tus: "Your",
    acciones: "Actions",
    grabar_selftape: "Record Self-Tape",
    mensajes: "Messages",
    ayuda: "Help",
    editar: "Edit",
    info_basica: "Basic information",
    media: "Media",
    credito: "Credit",
    credito_destacado: "Featured",
    creditos_destacados: "Featureds",
    habilidades: "Skills",
    habilidad: "Skill",
    medidas: "Measurements",
    activos: "Assets",
    preferencias_roles: "Role preferences",
    galeria_imagenes: "Image gallery",
    agregar: "Add",
    aniadir: "Add",
    imagen: "Image",
    imagenes: "Images",
    video: "Video",
    audio: "Audio",
    selftape: "Selftape",
    usuario_no_ha_capturado: `You haven't captured any [TYPE] yet`,
    llenar_todos_los_campos: `Please fill all the fields before attempting to add the [TYPE]`,
    titulo: "Title",
    rol: "Role",
    director: "Director",
    anio: "Year",
    clip: "Clip",
    destacado: "Featured",
    mascota: "Pet",
    mascotas: "Pets",
    tipo: "Type",
    raza: "Breed",
    tamanio: "Size",
    vehiculos: "Vehicles",
    marca: "Brand",
    modelo: "Model",
    color: "Color",
    vestuarios: "Clothing",
    tipo_especifico: "Specific Type",
    descripcion: "Description",
    props: "Props",
    equipo_deportivo: "Sports Equipment",
    apariencia: "Appearance",
    rango_de_edad_a_interpretar: "Age range to portray",
    se_identifica_como: "Identifies as",
    interesado_en_interpretar: "Interested in performing",
    apariencia_etnica: "Ethnic appearance",
    nacionalidad_etnia: "Nationality / Ethnicity",
    color_de_cabello: "Hair Color",
    dispuesto_a_cambiar_de_color_de_cabello: "Willing to change hair color",
    estilo_de_cabello: "Hairstyle",
    dispuesto_a_cortar_cabello: "Willing to cut hair",
    vello_facial: "Facial hair",
    dispuesto_a_crecer_o_afeitar_vello_facial:
      "Willing to grow or shave facial hair",
    color_de_ojos: "Eye color",
    tatuajes: "Tattoos",
    piercings: "Piercings",
    gemelo_o_trillizo: "Twin or Triplet",
    atributos_o_condiciones_unicas: "Unique attributes or conditions",
    medidas_vestuario: "Clothing Measurements",
    generales: "General",
    hombre: "Man",
    mujer: "Woman",
    nino: "Boy",
    nina: "Girl",
    entrepierna: "Crotch",
    guantes: "Gloves",
    sombrero: "Hat",
    pecho: "Chest",
    cuello: "Neck",
    mangas: "Sleeves",
    saco: "Jacket",
    playera: "Shirt",
    calzado: "Shoes",
    vestido: "Dress",
    busto: "Bust",
    copa: "Cup",
    cadera: "Hip",
    pants: "Pants",
    bebe: "Baby",
    mes: "Month",
    meses: "gestation weeks",
    largo: "length",
    tipo_de_trabajo: "Type of work",
    trabajo_de_extra: "Work as an extra",
    locacion_de_trabajo_principal: "Main Work Location",
    locaciones_de_trabajo_adicionales: "Additional Work Locations",
    interes_en_proyectos_pagados: "Interest in paid projects",
    interes_en_proyectos_no_pagados: "Interest in unpaid projects",
    nombre_de_representante: `Representative's Name`,
    documentos: "Documents",
    disponibilidad_para: "Availability for",
    otras_profesiones: "Other professions",
    meses_de_embarazo: "Months of pregnancy",
    embarazo: "Pregnancy",
    pagina_web: "Webpage",
    links_a_redes: "Links to social media",
    success_update_alert: "Alert successfully updated.",
    success_delete_alert: "Alert successfully deleted.",
    success_update_talento: "Talent successfully updated.",
    success_update_cazatalento: "Talent scout successfully updated.",
    success_update_representante: "Representative successfully updated.",
    warning_rango_fechas: "Please add the second date before proceeding.",
    warning_fecha_individual: "Please add a valid date.",
    success_update_creditos: "Credits successfully saved.",
    success_application_talento_created:
      "Application for this role successfully created.",
    success_update_medidas: "Measurements successfully updated.",
    calzado_ninos: "Children Shoes",
    acerca_de: "About Us",
    dialog_medidas_vestuario_subtitulo:
      "Choose the category that applies to you.",
  },
  es: {
    agencia_publicidad: "Agencia de publicidad",
    casa_productora: "Casa Productora",
    productor: "Productor",
    nuevo_proyecto: "Nuevo Proyecto",
    alertas: "Tus alertas",
    agenda_virtual: "Virtual diary",
    mis_proyectos: "My projects",
    editar_perfil: "Edit profile",
    fecha: "fecha",
    bienvenido: "Bienvenido",
    atencion: "Atención",
    activar: "Activar",
    publico: "Publico",
    privado: "Privado",
    lineas: "Lineas",
    no_visto: "No Visto",
    visto: "Visto",
    audicion: "Audición",
    status: "Estado",
    campo_no_definido: "No esta definido el [N], por favor contacta a soporte",
    ciudad: "Ciudad",
    estado: "Estado",
    no_tienes_elementos: "No tienes ningun(a) [N]",
    revisa: "Revisa",
    locacion_de_casting_y_fechas: "Locación de casting y fechas",
    locacion_de_filmacion_y_fechas: "Locación de filmación y fechas",
    presentacion_solicitud: "Presentación de solicitud",
    informacion_trabajo_y_notas: "Información del trabajo/notas",
    requisitos: "Requisitos",
    archivos_adicionales: "Archivos adicionales",
    desnudos_o_situaciones_sexuales: "Desnudos o situaciones sexuales",
    detalles: "Detalles",
    tu: "Tu",
    aplicacion: "Aplicación",
    aplicaciones: "Aplicaciónes",
    nota: "Nota",
    una: "Una",
    aplicado: "Aplicado",
    aplicar: "Aplicar",
    no_especificado: "No Especificado",
    fecha_limite_entrega_de_aplicaciones:
      "Fecha límite entrega de aplicaciones",
    compatibilidad_text: "de compatibilidad con tu perfil",
    aceptando_aplicaciones_de: "Aceptando aplicaciones de",
    inicio_de_proyecto: "Inicio de proyecto",
    en: "En",
    proyecto_por: "Proyecto Por",
    ver: "Ver",
    desde_hasta: "De [N1] a [N2]",
    cerrar: "Cerrar",
    pagado: "Pagado",
    no_pagado: "No Pagado",
    de: "De",
    confirmar: "Confirmar",
    todos: "Todos",
    rango_edad: "Rango Edad",
    genero_rol: "Genero Rol",
    tipo_rol: "Tipo Rol",
    preferencia_pago: "Preferencia Pago",
    buscar: "Buscar",
    PAGINADOR_RESULTS_LABEL: "[N1] de [N2] resultados totales",
    PAGINADOR_ENTRIES_PER_PAGE: "Ver [N] resultados por página",
    pagina: "Página",
    filtros: "Filtros",
    FILES_ERRORS_FILE_ALREADY_EXISTS: "El archivo ya habia sido agregado",
    FILES_ERRORS_FILE_TOO_BIG:
      "El archivo super el limite maximo de espacio de [SIZE] kb",
    FILES_ERRORS_MAX_FILES_REACHED:
      "El maximo de archivos permitido es [MAX_FILES]",
    particularidades: "Particularidades",
    visibilidad: "Visibilidad",
    profesion: "Profesion",
    otro: "Otro",
    contacto: "Contacto",
    principal: "Principal",
    adicional: "Adicional",
    seleccionar_todos: "Seleccionar Todos",
    registros_por_pagina: "Registros por pagina",
    o: "o",
    pagina_anterior: "Página Anterior",
    siguiente_pagina: "Siguiente Página",
    regresar_paso: "Paso previo",
    paso_siguiente: "Siguiente paso",
    guardar_y_terminar_mas_tarde: "Guardar y terminar más tarde",
    finalizar: "Finalizar",
    nombre: "Nombre",
    union: "Unión",
    ubicacion: "Ubicación",
    biografia: "Biografía",
    field_cant_be_empty: "El [CAMPO] no puede estar vacio",
    cambiar: "Cambiar",
    foto: "Foto",
    edad: "Edad",
    eliminar: "Eliminar",
    tipo_proyecto: "Tipo Proyecto",
    agencia: "Agencia",
    telefono: "Teléfono",
    correo_electronico: "Correo electrónico",
    archivo: "Archivo",
    carta_responsiva: "Carta Responsiva",
    cv: "CV",
    chico: "Chico",
    mediano: "Mediano",
    grande: "Grande",
    subir: "Subir",
    arrastrar_archivos: "Arrastrar archivo(s) al recuadro",
    si: "Si",
    no: "No",
    cerrar_sesion: "Cerrar Sesión",
    selecciona_una_opcion: "Selecciona una opción",
    cancelar: "Cancelar",
    guardar: "Guardar",
    no_registros: "No hay registros",
    descargar: "Descargar",
    proximamente: "proximamente",
    conoce_mas: "conoce más",
    çazatalentos: "Cazatalentos",
    talento: "Talento",
    representante: "Representante",
    paso: "Paso",
    peso: "Peso",
    altura: "Altura",
    perfil: "Perfil",
    tus_aplicaciones: "Tus Aplicaciones",
    tus: "Tus",
    acciones: "Acciones",
    grabar_selftape: "Grabar Self-Tape",
    mensajes: "Mensajes",
    ayuda: "Ayuda",
    editar: "Editar",
    info_basica: "Información básica",
    media: "Media",
    credito: "Crédito",
    credito_destacado: "Destacado",
    creditos_destacados: "Destacados",
    habilidades: "Habilidades",
    habilidad: "Habilidad",
    medidas: "Medidas",
    activos: "Activos",
    preferencias_roles: "Preferencia de roles",
    galeria_imagenes: "Galería de imágenes",
    agregar: "Agregar",
    aniadir: "Añadir",
    imagen: "Imagen",
    imagenes: "Imagenes",
    video: "Video",
    audio: "Audio",
    selftape: "Selftape",
    usuario_no_ha_capturado: "No has capturado aún ningún [TYPE]",
    llenar_todos_los_campos:
      "Por favor llena todos los campos antes de intentar agregar el [TYPE]",
    titulo: "Titulo",
    rol: "Rol",
    director: "Director",
    anio: "Año",
    clip: "Clip",
    destacado: "Destacado",
    mascota: "Mascota",
    mascotas: "Mascotas",
    tipo: "Tipo",
    raza: "Raza",
    tamanio: "Tamaño",
    vehiculos: "Vehiculos",
    marca: "Marca",
    modelo: "Modelo",
    color: "Color",
    vestuarios: "Vestuarios",
    tipo_especifico: "Tipo Especifico",
    descripcion: "Descripcion",
    props: "Props",
    equipo_deportivo: "Equipo Deportivo",
    apariencia: "Apariencia",
    rango_de_edad_a_interpretar: "Rango de edad a interpretar",
    se_identifica_como: "Se identifica como",
    interesado_en_interpretar: "Interesado en interpretar",
    apariencia_etnica: "Apariencia étnica",
    nacionalidad_etnia: "Nacionalidad / Etnia",
    color_de_cabello: "Color de Cabello",
    dispuesto_a_cambiar_de_color_de_cabello:
      "Dispuesto a cambiar de color de cabello",
    estilo_de_cabello: "Estilo de Cabello",
    dispuesto_a_cortar_cabello: "Dispuesto a cortar cabello",
    vello_facial: "Vello Facial",
    dispuesto_a_crecer_o_afeitar_vello_facial:
      "Dispuesto a crecer o afeitar vello facial",
    color_de_ojos: "Color de ojos",
    tatuajes: "Tatuajes",
    piercings: "Piercings",
    gemelo_o_trillizo: "Gemelo o trillizo",
    atributos_o_condiciones_unicas: "Atributos o condiciones únicas",
    medidas_vestuario: "Medidas Vestuario",
    generales: "Generales",
    hombre: "Hombre",
    mujer: "Mujer",
    nino: "Niño",
    nina: "Niña",
    entrepierna: "Entrepierna",
    guantes: "Guantes",
    sombrero: "Sombrero",
    pecho: "Pecho",
    cuello: "Cuello",
    mangas: "Mangas",
    saco: "Saco",
    playera: "Playera",
    calzado: "Calzado",
    vestido: "Vestido",
    busto: "Busto",
    copa: "Copa",
    cadera: "Cadera",
    pants: "Pants",
    bebe: "Bebé",
    mes: "Mes",
    meses: "Semanas de gestación",
    largo: "Largo",
    tipo_de_trabajo: "Tipo de trabajo",
    trabajo_de_extra: "Trabajo de Extra",
    locacion_de_trabajo_principal: "Locación de Trabajo Principal",
    locaciones_de_trabajo_adicionales: "Locaciónes de Trabajo Adicionales",
    interes_en_proyectos_pagados: "Interés en proyectos pagados",
    interes_en_proyectos_no_pagados: "Interés en proyectos no pagados",
    nombre_de_representante: "Nombre de Representante",
    documentos: "Documentos",
    disponibilidad_para: "Disponibilidad para",
    otras_profesiones: "Otras profesiones",
    meses_de_embarazo: "Meses de embarazo",
    embarazo: "Embarazo",
    pagina_web: "Página web",
    links_a_redes: "Link a redes sociales",
    success_update_alert: "Se actualizo la alerta con exito",
    success_delete_alert: "Se elimino la alerta con exito",
    success_update_talento: "Se actualizo el talento con exito",
    success_update_cazatalento: "Se actualizo el cazatalento con exito",
    success_update_representante: "Se actualizo el representante con exito",
    warning_rango_fechas:
      "Por favor agregar la segunda fecha antes de continuar",
    warning_fecha_individual: "Por favor agrega una fecha valida",
    success_update_creditos: "Se guardo los creditos con exito",
    success_application_talento_created:
      "Se creo la aplicacion para este rol con exito",
    success_update_medidas: "Se actualizaron las medidas con exito",
    calzado_ninos: "Calzado Niños",
    acerca_de: "Acerca de",
    dialog_medidas_vestuario_subtitulo:
      "Elige la categoría que aplique para ti.",
  },
};

const TEXTS_BY_PATHNAME: {
  [path: string]: { [lang: string]: { [key: string]: string } };
} = {
  "/": {
    en: {
      slide_1: `<p className="h2">MAKE FILMS AND MORE</p>
            <p>"When you embark on a project, a dream, a goal, every piece is important, and like a puzzle, it's crucial to find the pieces that fit together and add value to your project.</p>
            <p>In Talent Corner®, discover incredible tools that will help you bring that vision to reality. Don't let anyone close the door on you and create opportunities that many can only imagine!"</p>`,
      slide_2: `<p className="m-0 talent_corner">
            Talent Corner® is a digital platform that functions as a <strong>Match Maker</strong> tool in various areas and fields of production, enabling the creation, filmmaking, or showcasing of your talent. It brings together aspiring individuals who are looking to take their first steps in the artistic world, whether independently or professionally, as well as experienced individuals seeking to facilitate, streamline, and carry out their film productions in a more organized and intelligent manner.
            <br /><br />
            Talent Corner® consists of 3 different sections, each with tools targeting different audiences, all encompassing the same community with a shared purpose in this Talent Corner.
            <br /><br />
            These sections are: <em>EZ-CAST</em>, <em>TREEHOUSE</em>, and <em>TALENT+</em>.
            <br /><br />
            Talent Corner® offers professional tools and formats at your disposal to collaborate on and execute projects of all kinds, from script to the big screen! Talent Corner® also serves as a self-promotion tool!</p>`,
      slide_4: `EZ-CAST, the place for those who want to discover and be discovered, CASTINGS`,
      slide_6: `A better way to search, find, and rent locations!`,
      slide_8: `Find the right freelance professional to start working on your project in minutes. A whole world of freelance talent at your fingertips.`,
    },
    es: {
      slide_1: `<p className="h2">HAZ CINE Y MÁS</p>
            <p>“Cuando te embarcas en un proyecto, un sueño, una meta, cada pieza es importante y como un  rompecabezas, es clave encontrar las piezas que embonen y sumen a tu proyecto.</p>
            <p>En Talent Corner® descubre herramientas increíbles que te ayudarán a traer esa visión a la realidad. ¡Que nadie te cierre la puerta y crea las oportunidades que muchos solo imaginan!” </p>`,
      slide_2: `<p className="m-0 talent_corner">
            Talent Corner® es una plataforma digital que funciona como herramienta de Match Maker a nivel producción en diferentes espacios y ámbitos, para crear, hacer cine o exponer tu talento, reuniendo así a aspirantes que buscan dar sus primeros pasos en el mundo artístico tanto a nivel independiente como profesional, así como personas con experiencia que busquen facilitar, agilizar y realizar sus producciones cinematográficas de una manera más organizada e inteligente.
            <br /><br />
            Talent Corner® consta de 3 diferentes secciones, herramientas que van dirigidas a diferente público, englobando un mismo gremio con una misma finalidad en esta Esquina del Talento.
            <br /><br />
            Estas son: EZ-CAST, TREEHOUSE Y TALENT +
            <br /><br />
            Talent Corner® pone a su disposición herramientas y formatos profesionales para sumar y ejecutar proyectos de todo tipo, ¡Del guión a la pantalla grande! ¡Talent Corner®  sirve también como herramienta de AUTOPROMOCIÓN!</p>`,
      slide_4: `EZ-CAST el lugar para los que quieren encontrar y ser encontrados, CASTINGS`,
      slide_6: `¿Una mejor manera de buscar, encontrar, rentar locaciones!`,
      slide_8: `Encuentra al profesional independiente adecuado para comenzar a trabajar en su proyecto en minutos. Todo un mundo de talento autónomo a tu alcance.`,
    },
  },
  "/registro": {
    en: {
      Titulo: "EZ-CAST REGISTRATION",
      return: "BACK TO EZ-CAST INFORMATION",
      paso_1: "1",
      crea_perfil: "Create your profile",
      nombre: "Name*",
      apellidos: "Lastname*",
      usuario: "User*",
      mail: "E-mail",
      contra: "Password",
      confirma_contra: "Confirm Password",
      registrar_con: "Or register with",
      siguiente_paso: "Next Step ",
      nombre_corto: "The name is too short",
      apellido_corto: "The lastname is too short",
      usuario_corto: "The username is too short",
      mail_invalido: "The email is invalid",
      contra_corta: "The password is too short",
      contra_diferente: "The passwords are not the same",
      paso_2: "2",
      tipo_membresia: "Type of membresia",
      gratis: "Free",
      anual: "Annual",
      mensual: "Monthly",
      pago: "Pay",
      forma_pago: "Way to pay",
      success_login: "Successful Authentication",
      validar_campos_form: "Please first correct the errors in the form.",
      no_ha_aceptado_terminos:
        "You have not accepted the terms and conditions.",
      errores_en_formulario:
        "There are errors in the form, please correct them and try again.",
    },
    es: {
      Titulo: "REGISTRO EZ-CAST",
      return: "REGRESAR A INFORMACIÓN EZ-CAST",
      paso_1: "1",
      crea_perfil: "Crea tu perfil",
      nombre: "Nombre*",
      apellidos: "Apellidos*",
      usuario: "Usuario*",
      mail: "Correo electrónico",
      contra: "Contraseña",
      confirma_contra: "Confirmar Contraseña",
      registrar_con: "O registrate con",
      siguiente_paso: "Siguiente Paso ",
      nombre_corto: "El nombre es demasiado corto",
      apellido_corto: "El apellido es demasiado corto",
      usuario_corto: "El usuario es demasiado corto",
      mail_invalido: "El email es invalido",
      contra_corta: "La contraseña es demasiado corta",
      contra_diferente: "Las contraseñas no son la misma",
      paso_2: "2",
      tipo_membresia: "Tipo de membresía",
      gratis: "Gratis",
      anual: "Anual",
      mensual: "Mensual",
      pago: "Pago",
      forma_pago: "Forma de pago",
      success_login: "Autenticacion Exitosa",
      validar_campos_form:
        "Por favor primero corrige los errores del formulario",
      no_ha_aceptado_terminos: "No haz aceptado los terminos y condiciones",
      errores_en_formulario:
        "Hay errores en el formulario, por favor corrigelos y intenta de nuevo",
    },
  },
  "/login": {
    en: {
      no_tienes_cuenta: "You do not have an account?",
      registrate: "Sign up here",
      mail: "User / Email",
      password: "Password",
      fgtpswd: "Forgot your password?",
      restablecer: "Restore",
      ingresar_como: "Login as",
      accede_con: "Or access with",
      necesitas_ayuda: "Need help?",
      accede_a: "Access our",
      tutoriales: "tutorials and frequently asked questions",
      descripción_cazatalentos:
        'Profile for the person who seeks to "hunt" a person who meets the requirements and the talent that he needs.',
      descripcion_talento:
        "Profile for the person looking to appear on screen and film projects.",
      descripcion_representante:
        "Profile for the person who seeks to facilitate the connection with their talents and find more opportunities for them.",
      success_login: "Successful Authentication",
      error_login: "Incorrect username or password.",
      error_form: "Please correct the form before proceeding with the login.",
    },
    es: {
      no_tienes_cuenta: "No tienes cuenta?",
      registrate: "Registrate aquí",
      mail: "Usuario / Email",
      password: "Contraseña",
      fgtpswd: "Olvido su contraseña?",
      restablecer: "Restablecer",
      ingresar_como: "Ingresar como",
      accede_con: "O accede con",
      necesitas_ayuda: "Necesitas ayuda?",
      accede_a: "Accede a nuestros",
      tutoriales: "tutoriales y preguntas frecuentes.",
      descripción_cazatalentos:
        "Perfil para la persona que busca “cazar” a una persona que cumpla con los requerimientos y el talento que éste necesita.",
      descripcion_talento:
        "Perfil para la persona que busca aparecer en pantalla y proyectos de filmación.",
      descripcion_representante:
        "Perfil para la persona que busca facilitar la conexión con sus talentos y encontrar más oportunidades para los mismos.",
      success_login: "Autenticacion Exitosa",
      error_login: "Usuario u contraseña incorrectos",
      error_form:
        "Por favor corrige el formulario antes de continuar con el inicio de sesion",
    },
  },
  "/inicio": {
    en: {
      proyectos_activos: "Active Projects",
      ahora_siendo_casteado: "Now being cast...",
      destacados: "Featured",
      ahora_castenado_en_ezcast: "Now casting on EZ-Cast",
      continuar_a_ezcast: "Continue to EZ-Cast",
    },
    es: {
      proyectos_activos: "Proyectos Activos",
      ahora_siendo_casteado: "Ahora siendo casteado…",
      destacados: "destacados",
      ahora_castenado_en_ezcast: "Ahora casteando en EZ-Cast",
      continuar_a_ezcast: "Continuar a EZ-Cast",
    },
  },
  "/talento/dashboard": {
    en: {},
    es: {},
  },
  "/talento/editar-perfil": {
    en: {
      step6_title: "Role Preferences And Compensations",
      step7_title: "Appareance Filters",
      nombre_union: `Union's Name`,
      eres_menor_de_edad: "Are you a minor",
      datos_representante: "Data of legal representative or guardian",
      info_medidas:
        "Later on, you can add clothing measurements in the final view of your profile",
      elegir_foto_perfil: "Select profile photo",
      info_basica_biografia_tooltip_title: "Tell us about yourself",
      info_basica_biografia_tooltip_body:
        "We recommend that you write a short text that describes your professional training and interests",
      info_basica_webpage:
        "Add here the link of your website or portfolio that best represents your work, remember that this link will be visible on your profile for Headhunters.",
      media_fotos_tooltip: "Test",
      media_videos_tooltip_titulo: "Add a videobook or reel.",
      media_videos_tooltip_body: `A reel consists of editing together a clip that highlights your on-stage moments from later works. We recommend being clear and direct, seeking the best quality in audio and video, and compiling your best works to contrast and showcase.`,
      media_audios_tooltip:
        "Showcase in a short audio your vocal ability; accents, imitations, voices, singing, etc...",
      mostrar_anio_en_perfil: "Show year in profile",
      creditos_credito_destacado_tooltip:
        "You can highlight up to 3 credits, these will be visible to the Headhunter.",
      creditos_credito_destacado_max_validacion:
        "You can only have 3 featured credits at a time, remove another to be able to feature another",
      tipo_vehiculo: "Vehicle Type",
      activos_vehiculos_max_validacion:
        "You can only have up to 5 vehícles, if you want to add another one first you`ll need to delete one",
      tipo_mascota: "Pet Type",
      activos_mascotas_max_validacion:
        "You can only have up to 5 pets, if you want to add another one first you`ll need to delete one",
      tipo_vestuario: "Clothing Type",
      tipo_vestuario_especifico: "Specific Clothing Type",
      tipo_prop: "Prop Type",
      tipo_equipo: "Equipment Type",
      activos_equipo_deportivo_max_validacion:
        "You can only have up to 5 sport equipment, if you want to add another one first you`ll need to delete one",
      activos_title_tooltip_title: `From your house to the set`,
      activos_title_tooltip_body: `Add the assets you have to the production team, these can be very beneficial and turn production around as added value to your talent, these can be costumes, props, vehicles, etc...`,
      info_basica_cv_tooltip:
        "Remember to add the most up-to-date version of your resume in PDF format",
      habilidades_tooltip:
        "Include all the skills that differentiate you from others. A Headhunter may be looking for a role with your skills!",
      preferencias_rol_tooltip:
        "A role is a role that a person represents within a story, this character can be fictional or real.",
      preferencias_rol_alerta:
        "We recommend that you do not limit yourself to a single type of role to have more chances of being selected.",
      preferencias_rol_tipo_de_trabajo_tooltip:
        "Select those options that fit your skills",
      preferencias_rol_interesado_trabajo_extra_title:
        "Are you interested in extra work",
      preferencias_rol_interesado_trabajo_extra_tooltip: `Do you have much or little experience and knowledge within a set? Working extra can open many doors for you and give you knowledge in the field, in addition to being an important and always useful role in any production.`,
      preferencias_rol_interesado_trabajo_extra_subtitle: `If you indicate interest in working as an extra, you will appear in the Director's extras search`,
      preferencias_rol_interes_en_proyectos: "Interest in projects",
      preferencias_rol_interes_en_proyectos_tooltip:
        "We recommend selecting both options to increase your chances of being recruited. Do not limit yourself and generate contacts, experience, and new professional credits.",
      preferencias_rol_locacion: "Main Work Location + Additional",
      preferencias_rol_locacion_tooltip:
        "Add the State that you inhabit or frequent the most as Main Location, it also includes an additional location and expands your work possibilities.",
      preferencias_rol_locacion_button: "Add another location",
      preferencias_rol_locacion_empty_locacion_validation:
        "Please select another location before trying to add it",
      preferencias_rol_documentos_subtitulo:
        "¿What official documents and licenses do you have?",
      preferencias_rol_disponibilidad_subtitulo:
        "Some directors request specific activities, let them know if you are willing to do them",
      preferencias_rol_otras_profesiones: "Other Professions",
      preferencias_rol_otras_profesiones_tooltip: `Add any jobs you've had or have outside of the medium. Your skill might be being sought for a project role right now!`,
      filtros_apariencia_alerta:
        "This will not be visible on your profile, but will appear in searches based on what you select.",
      filtros_apariencias_tatuajes_subtitulo: `Do you have distinctive tattoos? It's your chance to inform the casting directors`,
      filtros_apariencias_piercings_lugar: "Placement",
      filtros_apariencias_piercings_subtitulo: `Do you have any piercings? It's your chance, let the casting director know`,
      filtros_apariencias_eres_gemelo_o_trillizo:
        "Are you an identical twin or triplet",
      filtros_apariencias_particularidades_subtitle:
        "Sometimes directors look for specific attributes, let them know if you have any of the following",
      filtros_apariencias_particularidades_otro_tipo:
        "Description of another type of peculiarity",
      filtros_apariencias_empty_fields_piercings:
        "The fields of place and description cannot be empty",
      filtros_apariencias_empty_fields_tattoos:
        "The fields of visibility and description cannot be empty",
      success_save_info_gral: "General information successfully saved.",
      success_save_medios: "Files successfully saved.",
      success_save_creditos: "Credits successfully saved.",
      success_save_habilidades: "Skills successfully saved.",
      success_save_activos: "Assets successfully saved.",
      success_save_preferencias: "Preferences successfully saved.",
      success_save_filtros: "Appearance filters successfully saved.",
      error_upload_image: "An image could not be uploaded.",
      error_upload_image_with_name: "The image [N1] could not be uploaded.",
      error_upload_audio: "An audio could not be uploaded.",
      error_upload_audio_with_name: "The audio [N1] could not be uploaded.",
      error_upload_video: "A video could not be uploaded.",
      error_upload_video_with_name: "The video [N1] could not be uploaded.",
      error_upload_credito: "A credit could not be uploaded.",
      error_upload_credito_with_name: "The credit [N1] could not be uploaded.",
    },
    es: {
      step6_title: "Preferencia de rol y compensación",
      step7_title: "Filtros de Apariencia",
      nombre_union: "Nombre Unión",
      eres_menor_de_edad: "Eres menor de edad",
      datos_representante: "Datos de representante o tutor legal",
      info_medidas:
        "Más adelante, puedes agregar medidas para vestuario en la vista final de tu perfil",
      elegir_foto_perfil: "Eligir foto de perfil",
      info_basica_biografia_tooltip_title: "Cuentanos sobre ti",
      info_basica_biografia_tooltip_body:
        " Te recomendamos escribir un texto breve que describa tu formación profesional e intereses",
      info_basica_webpage:
        "Añade aquí el link de tu página web o portafolio que mejor represente tu trabajo, recuerda que este link será visible en tu perfil para los Cazatalentos.",
      media_fotos_tooltip: "Prueba",
      media_videos_tooltip_titulo: "Añade un videobook o Reel",
      media_videos_tooltip_body: `Un reel consiste en montar un clip editado que destaque tus
            momentos en escena de trabajos posteriores, te recomendamos
            ser claro y directo, buscar la mejor calidad en Audio y
            Video contrastando y recopilando tus mejores trabajos`,
      media_audios_tooltip:
        "Resalta en un breve audio tu habilidad vocal; acentos, imitaciones, voces, canto, etc...",
      mostrar_anio_en_perfil: "Mostrar Año en Perfil",
      creditos_credito_destacado_tooltip:
        "Puedes destacar hasta 3 créditos, estos estarán a la vista del Cazatalento.",
      creditos_credito_destacado_max_validacion:
        "Solo puedes tener 3 créditos destacados al mismo tiempo, quita otro para poder destacar otro.",
      tipo_vehiculo: "Tipo Vehiculo",
      activos_vehiculos_max_validacion:
        "Solo puedes tener hasta 5 vehículos, si deseas agregar otro por favor borra algún vehículo",
      tipo_mascota: "Tipo Mascota",
      activos_mascotas_max_validacion:
        "Solo puedes tener hasta 5 mascotas, si deseas agregar otro por favor borra algúna mascota",
      tipo_vestuario: "Tipo Vestuario",
      tipo_vestuario_especifico: "Tipo Vestuario Especifico",
      tipo_prop: "Tipo Prop",
      tipo_equipo: "Tipo Equipo",
      activos_equipo_deportivo_max_validacion:
        "Solo puedes tener hasta 5 mascotas, si deseas agregar otro por favor borra algúna mascota",
      activos_title_tooltip_title: `De tu casa al set`,
      activos_title_tooltip_body: `Suma al equipo de producción con los activos que cuentes, estos pueden ser muy beneficiosos y dar un giro a la producción como plus valía a tu talento, estos pueden ser vestuario, props, vehículos, etc...`,
      info_basica_cv_tooltip:
        "Recuerda añadir la versión más actualizada de tu currículum en formato PDF",
      habilidades_tooltip:
        "Incluye todas las habilidades que te diferencien de los demás. ¡Un Cazatalentos puede estar buscando un rol con tus habilidades!",
      preferencias_rol_tooltip:
        "Un rol es un papel que una persona representa dentro de una historia, este personaje puede ser ficticio o real.",
      preferencias_rol_alerta:
        "Te recomendamos no cerrarte a un solo tipo de rol para tener más oportunidades de ser seleccionado.",
      preferencias_rol_tipo_de_trabajo_tooltip:
        "Selecciona aquellas opciones que vayan de acuerdo a tus habilidades",
      preferencias_rol_interesado_trabajo_extra_title:
        "Estás interesado en trabajo de extra",
      preferencias_rol_interesado_trabajo_extra_tooltip:
        "Tienes mucha o poca experiencia y conocimiento dentro de un set? Trabajar de extra puede abrirte muchas puertas y darte conocimiento en el campo, además de que es un rol importante y siempre útil en toda producción.",
      preferencias_rol_interesado_trabajo_extra_subtitle:
        "Si indicas interés en trabajar como extra, aparecerás en la búsqueda de extras del Director",
      preferencias_rol_interes_en_proyectos: "Interés en proyectos",
      preferencias_rol_interes_en_proyectos_tooltip:
        "Te recomendamos seleccionar ambas opciones, para aumentar tus posibilidades de ser reclutado. No te limites y genera contactos, experiencia, y nuevos créditos profesionales.",
      preferencias_rol_locacion: "Locación de Trabajo Principal + Adicionales",
      preferencias_rol_locacion_tooltip:
        "Agrega el Estado que habites o frecuentes más como Locación Principal, también incluye una locación adicional y amplía tus posibilidades de trabajo.",
      preferencias_rol_locacion_button: "Agregar otra localizacion",
      preferencias_rol_locacion_empty_locacion_validation:
        "Por favor selecciona otra localizacion antes de intentar agregarla",
      preferencias_rol_documentos_subtitulo:
        "¿Qué documentos oficiales y licencias tienes?",
      preferencias_rol_disponibilidad_subtitulo:
        "Algunos directores solicitan actividades específicas, déjales saber si estás dispuesto a realizarlas",
      preferencias_rol_otras_profesiones: "Otras Profesiones",
      preferencias_rol_otras_profesiones_tooltip:
        "Añade algún trabajo que hayas tenido o tengas fuera del medio ¡Tu habilidad podría estar siendo buscada ahora mismo para el rol de un proyecto!",
      filtros_apariencia_alerta:
        "Esto no será visible en tu perfil, pero aparecerá en las búsquedas basadas en lo que selecciones.",
      filtros_apariencias_tatuajes_subtitulo:
        "¿Tienes tatuajes distintivos? Es tu oportunidad de informar a los directores de casting.",
      filtros_apariencias_piercings_lugar: "Lugar",
      filtros_apariencias_piercings_subtitulo:
        "¿Tienes algún piercing? Es tu oportunidad, hazle saber al director de casting.",
      filtros_apariencias_eres_gemelo_o_trillizo:
        "Eres gemelo o trillizo idéntico",
      filtros_apariencias_particularidades_subtitle:
        "Algunas veces los directores buscan atributos específicos, déjales saber si tienes alguno de los siguientes",
      filtros_apariencias_particularidades_otro_tipo:
        "Descripcion otro tipo de particularidad",
      filtros_apariencias_empty_fields_piercings:
        "El campo de lugar y descripcion no pueden estar vacios",
      filtros_apariencias_empty_fields_tattoos:
        "El campo de visibilidad y descripcion no pueden estar vacios",
      success_save_info_gral: "Se guardo la informacion general con exito",
      success_save_medios: "Se guardaron los archivos con exito",
      success_save_creditos: "Se guardo los creditos con exito",
      success_save_habilidades: "Se guardaron las habilidades con exito",
      success_save_activos: "Se guardaron los activos con exito",
      success_save_preferencias: "Se guardaron las preferencias con exito",
      success_save_filtros: "Se guardaron los filtros de apariencias con exito",
      error_upload_image: "Una imagen no se pudo subir",
      error_upload_image_with_name: "La imagen [N1] no se pudo subir",
      error_upload_audio: "Un audio no se pudo subir",
      error_upload_audio_with_name: "El audio [N1] no se pudo subir",
      error_upload_video: "Un video no se pudo subir",
      error_upload_video_with_name: "El video [N1] no se pudo subir",
      error_upload_credito: "Un credito no se pudo subir",
      error_upload_credito_with_name: "El credito [N1] no se pudo subir",
    },
  },
  "/talento/billboard": {
    en: {
      auto_rellenado_text: "Auto-fill based on profile",
      por_rol: "By Role",
      por_proyecto: "By Project",
      filtros_aplicados: "Applied Filters",
      validacion_filtro_con_autorellenado:
        "You cannot remove this filter when the autofill option is enabled",
      no_opciones_seleccionadas: "There is no option selected yet",
      no_filtros: "There are no filter added yet",
      no_proyectos_titulo:
        "It seems like you are referring to the fact that there are no projects that match your profile",
      no_proyectos_body:
        "Make sure to keep your profile up to date so that we can provide you with projects that match your characteristics.",
    },
    es: {
      auto_rellenado_text: "Auto-rellenar basado en perfil",
      por_rol: "Por Rol",
      por_proyecto: "Por Proyecto",
      filtros_aplicados: "Filtros Aplicados",
      validacion_filtro_con_autorellenado:
        "No se puede quitar este filtro cuando esta activada la opcion de autorellenado",
      no_opciones_seleccionadas: "No se han seleccionado opciones",
      no_filtros: "No se ha agregado ningun filtro",
      no_proyectos_titulo: "No hay proyectos que se ajusten a tu perfil",
      no_proyectos_body:
        "Asegurate de tener tu perfil al corriente para asi poder brindarte los proyectos de acuerdo a tus carateristicas.",
      no_options_selected: "No se han seleccionado opciones",
    },
  },
  "/talento/aplicaciones": {
    en: {
      no_aplicaciones_title: "You have not applied to any project",
      no_aplicaciones_body:
        "Continue adding appearance filters, highlighting your skills, showcasing your credits, and applying to different projects on the Casting Billboard that EZ-Cast by Talent Corner has for you.",
    },
    es: {
      no_aplicaciones_title: "No has aplicado a ningún proyecto",
      no_aplicaciones_body:
        "Continúa agregando filtros de apariencia, remarca tus habilidades, activos créditos y aplica a los distintos proyectos en el Casting Billboard que EZ-Cast de Talent Corner tiene para ti.",
    },
  },
  "/talento/self-tape": {
    en: {
      title_text:
        "A self-tape is a technique used in the film industry where a person films themselves during a casting audition. Take advantage of this tool and record your auditions in seconds!",
      max_selftapes_reached:
        "Only a maximum of 6 self-tapes per user is allowed. Please delete one before attempting to record another",
      current_count_selftape:
        "You have [COUNT] self-tapes available in the Media Bank",
      ir_media_bank: "Go To Media Bank",
      record_selftape: "Record Self-Tape",
      recording: "Recording",
      deseas_guardar: "Do you want to save the Self-Tape",
      guardar_dialog_subtitle:
        "You will have the option to play and download it in the Media Bank",
      no_camera:
        "To use the self-tape function, you must grant permission to the application to access your camera",
      error_didnt_upload: "A video could not be uploaded.",
      error_didnt_upload_with_name: "The video [N1] could not be uploaded.",
      success_save_selftape_media: "The self-tape was successfully stored.",
    },
    es: {
      title_text:
        "Un self tape es una técnica utilizada en el mundo cinematográfico en la que una persona se filma a sí misma en una prueba de casting. ¡Saca ventaja de esta herramienta y graba tus audiciones en segundos!",
      max_selftapes_reached:
        "Solo se permite maximo 6 selftapes por usuario, por favor elimina uno antes de intentar grabar otro",
      current_count_selftape:
        "Tienes [COUNT] selftapes disponibles en el Media Bank",
      ir_media_bank: "Ir a Media Bank",
      record_selftape: "Grabar Self-Tape",
      recording: "Grabando",
      deseas_guardar: "Deseas guardar Self-Tape",
      guardar_dialog_subtitle:
        "Tendrás la posibilidad de reproducirlo y bajarlo en el Media Bank",
      no_camera:
        "Para usar la función de self-tape, debes dar permiso a la aplicación para acceder a tu cámara",
      error_didnt_upload: `Un video no se pudo subir`,
      error_didnt_upload_with_name: `El video [N1] no se pudo subir`,
      success_save_selftape_media: "Se almaceno el selftape con exito",
    },
  },
  "/talento/media-bank": {
    en: {
      dialog_selftape_titulo:
        "Select the video you want to upload for your self-tapes",
      selecciona_un_video: "Select a video",
      video_no_se_pudo_subir: "The video [N] couldn`t be uploaded",
      un_video_no_se_pudo_subir: "The video couldn`t be uploaded",
      no_haz_seleccionado_ningun_video: `You haven't selected any video`,
      limite_selftapes:
        "The self-tapes limit is 6; please delete one before attempting to save another",
      success_save_selftape_media: "The self-tape was successfully saved.",
      success_delete_selftape_media: "The self-tape was successfully deleted.",
      link_copied: "The link was copied.",
    },
    es: {
      dialog_selftape_titulo:
        "Selecciona el video que deseas subir a tus selftapes",
      selecciona_un_video: "Selecciona un video",
      video_no_se_pudo_subir: "El video [N] no se pudo subir",
      un_video_no_se_pudo_subir: "Un video no se pudo subir",
      no_haz_seleccionado_ningun_video: "No haz seleccionado ningun video",
      limite_selftapes:
        "El limite de selftapes es 6, por favor elimina uno antes de querer guardar otro",
      success_save_selftape_media: "Se almaceno el selftape con exito.",
      success_delete_selftape_media: "Se elimino el selftape con exito",
      link_copied: "Se copio el link",
    },
  },
  "/cazatalentos/dashboard": {
    en: {
      encabezado: "Requirements for approval:",
      destacados: "Featured",
      requisito_uno: "You will need to create specific roles.",
      requisito_dos: "Submit an abstract describing your project.",
      requisito_tres:
        "Include details of my characters including physical traits, personality and scene development.",
      requisito_cuatro:
        "If your project includes a minor, the character description must include the number of hours on set and details inherent to the character",
      requisito_cinco: "You will need to create specific roles.",
      requisito_seis: "Submit an abstract describing your project.",
      requisito_siete:
        "Include details of my characters including physical traits, personality and scene development.",
      requisito_ocho:
        "If your project includes a minor, the character description must include the number of hours on set and details inherent to the character",
      proyectos: "Projects",
      nuevo_proyecto: "New Project",
      activos: "Active",
      archivados: "Archived",
      no_tienes_proyectos: "You don't have any projects archived",
      aqui_apareceran:
        "Here will appear all the projects that you have placed as archived",
    },
    es: {
      encabezado: "Requisitos para aprobación:",
      destacados: "Destacados",
      requisito_uno: "Deberás crear roles específicos.",
      requisito_dos: "Presentar un resumen que describa tu proyecto.",
      requisito_tres:
        "Incluir detalles de mis personajes incluyendo rasgos físicos, personalidad y desarrollo en escena.",
      requisito_cuatro:
        "Si tu proyecto incluye a un menor de edad, la descripción del personaje deberá incluir el número de horas en set y detalles inherentes al personaje",
      requisito_cinco: "Deberás crear roles específicos.",
      requisito_seis: "Presentar un resumen que describa tu proyecto.",
      requisito_siete:
        "Incluir detalles de mis personajes incluyendo rasgos físicos, personalidad y desarrollo en escena.",
      requisito_ocho:
        "Si tu proyecto incluye a un menor de edad, la descripción del personaje deberá incluir el número de horas en set y detalles inherentes al personaje",
      proyectos: "Proyectos",
      nuevo_proyecto: "Nuevo Proyecto",
      activos: "Activos",
      archivados: "Archivados",
      no_tienes_proyectos: "No tienes ningún proyecto archivado",
      aqui_apareceran:
        "Aqui apareceran todos los proyectos que hayas colocado como archivados",
    },
  },
  "/cazatalentos/proyecto": {
    en: {
      comencemos: "Let's start!",
      info_gral: "General information",
      nombre_proyecto: "Project name*",
      sindicato: "Labor union*",
      tipo_proyecto: "Project Type*",
      contacto_casting: "Casting Contact",
      privacidad: "This information will not be shared with the public",
      director_de_casting: "Casting Director*",
      numero_telefono: "Phone number*",
      confirmar_correo: "Confirm Email",
      equipo_creativo: "Creative Team",
      detalles_adicionales: "",
      sinopsis: "Synopsis* ",
      agregar_archivo: "Add file",
      instruccion: "(Script, Storyboard or Contract)",
    },
    es: {
      comencemos: "¡Comencemos!",
      info_gral: "Información General",
      nombre_proyecto: "Nombre de proyecto*",
      sindicato: "Sindicato*",
      tipo_proyecto: "Tipo Proyecto*",
      contacto_casting: "Contacto de Casting",
      privacidad: "Esta información no se compartirá con el público",
      director_de_casting: "Director de casting*",
      numero_telefono: "Número de teléfono*",
      confirmar_correo: "Confirmar correo electrónico",
      equipo_creativo: "Equipo Creativo",
      detalles_adicionales: "Detalles adicionales",
      sinopsis: "Sinopsis* ",
      agregar_archivo: "Agregar Archivo",
      instruccion: "(Guión, Storyboard o Contrato)",
    },
  },
  "/cazatalentos/agenda-virtual/horario/[id]": {
    en: {},
    es: {},
  },
  "/cazatalentos/agenda-virtual/crear": {
    en: {},
    es: {},
  },
  "/admin/login": {
    en: {},
    es: {},
  },
  "/admin": {
    en: {},
    es: {},
  },
};

const useLang = (lang: string) => {
  const route = useRouter();

  if (route.pathname === "/admin") {
    lang = "es";
  }

  const [texts, setTexts] = useState<{ [key: string]: string }>({});

  useEffect(() => {
    if (TEXTS_BY_PATHNAME[route.pathname]) {
      const by_path = TEXTS_BY_PATHNAME[route.pathname];
      if (by_path) {
        const by_lang = by_path[lang];
        const common = COMMON_TEXTS[lang];
        setTexts(by_lang ? { ...by_lang, ...common } : {});
      } else {
        setTexts({});
      }
    } else {
      setTexts({});
    }
  }, [lang, route.pathname]);

  return texts;
};

export default useLang;
