export * from './shared'
export * from './layout'
export * from './home'
export * from './registro'
export * from './restablecer-contrasena'
export * from './ayuda'
export * from './componentes-dashboards'
export * from './slide'