const Constants = {
  TIPOS_USUARIO: {
    TALENTO: "TALENTO",
    CAZATALENTOS: "CAZATALENTOS",
    REPRESENTANTE: "REPRESENTANTE",
  },
  ESTADOS_ASIGNACION_AUDICION: {
    AUDICION_PENDIENTE: 'AUDICION_PENDIENTE',
    AUDICION_CONFIRMADO: 'AUDICION_CONFIRMADO',
    AUDICION_RECHAZADO: 'AUDICION_RECHAZADO',
    CALLBACK_PENDIENTE: 'CALLBACK_PENDIENTE',
    CALLBACK_CONFIRMADO: 'CALLBACK_CONFIRMADO',
    CALLBACK_RECHAZADO: 'CALLBACK_RECHAZADO',
  },
  ESTADOS_APLICACION_ROL: {
    NO_VISTO: 1,
    VISTO: 2,
    DESTACADO: 3,
    AUDICION: 4,
    CALLBACK: 5,
  },
  ESTADOS_ASIGNACION_HORARIO: {
    PENDIENTE: "Pendiente",
    CONFIRMADO: "Confirmado",
    RECHAZADO: "Inactivo",
    APROBADO: "Activo",
  },
  TIPOS_EMAILS: {
    INVITACION_TALENTO: "INVITACION_TALENTO",
    PASSWORD_RECOVERY: 'PASSWORD_RECOVERY'
  },
  ESTADOS_ROLES: {
    ARCHIVADO: "ARCHIVADO",
    SIN_FINALIZAR: "SIN_FINALIZAR",
  },
  ESTADOS_PROYECTO: {
    POR_VALIDAR: "POR_VALIDAR",
    ARCHIVADO: "ARCHIVADO",
    ENVIADO_A_APROBACION: "ENVIADO_A_APROBACION",
    APROBADO: "APROBADO",
    RECHAZADO: "RECHAZADO",
  },
  PATTERNS: {
    EMAIL: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/,
    URL: /^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$/,
  },
  PAGE_ERRORS: {
    USER_DONT_EXISTS: "USER_DONT_EXISTS",
    UNAUTHORIZED_USER_ROLE: "UNAUTHORIZED_USER_ROLE",
    NO_EDIT_PERMISSIONS: "NO_EDIT_PERMISSIONS",
  },
};

export default Constants;
